Description: Configuration for CANoe participant for SIL Kit Adapter SocketCAN Demo
Logging:
  Sinks:
    - Level: Info
      Type: Stdout
CanControllers:
 - Name: "CAN"
   Network: "CAN1"

Middleware:
  RegistryUri: silkit://192.168.56.101:8501